// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4K8gO5--Uy1J8vIiqLgNDVJRGNRL2B8o',
    appId: '1:565425662719:web:c7aa87c4fcf73907f67aca',
    messagingSenderId: '565425662719',
    projectId: 'newa-fest-app',
    authDomain: 'newa-fest-app.firebaseapp.com',
    storageBucket: 'newa-fest-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzznLEnkWsyWegT_TUCNS9wLCwPsw9JpY',
    appId: '1:565425662719:android:483f23f3d529ac41f67aca',
    messagingSenderId: '565425662719',
    projectId: 'newa-fest-app',
    storageBucket: 'newa-fest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6-xhV1OGxL2WmceULLC60xnSHsymLr_s',
    appId: '1:565425662719:ios:0466346a31873e6df67aca',
    messagingSenderId: '565425662719',
    projectId: 'newa-fest-app',
    storageBucket: 'newa-fest-app.firebasestorage.app',
    iosBundleId: 'com.example.newafest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4K8gO5--Uy1J8vIiqLgNDVJRGNRL2B8o',
    appId: '1:565425662719:web:a10df91b044ad53df67aca',
    messagingSenderId: '565425662719',
    projectId: 'newa-fest-app',
    authDomain: 'newa-fest-app.firebaseapp.com',
    storageBucket: 'newa-fest-app.firebasestorage.app',
  );
}
